Add Guards, Login, Admin Side Features, and Admin Ui
Daskom-Lab/daskomrec24 pull request #3
Opened 2024-01-17 07:34 UTC by DiyArc-350

**Fix**
- (models) : missing fillables field, minor typos

**Feature**
- (guards) : add admin and caas guards
- (routes) : configure route for admin 
- (login) : add AdminLogin and CaasLogin controller
- (admin) : add AdminController
- (admin) : add admin web template
- (datacaas) : add features to DataCaasController
- (shift) : add features to ShiftCotroller
- (plots) : add features to PlottingController
- (roles) : add features to RolesController

**Build**
- add maatwebsite/excel library
- modified composer.json (change maatwesite version)

2024-01-18 00:01 UTC, IritaSee requested changes
Sorry I havent check everything yet, I will be back soon, for now, please restore the example to as it is, since that act can spill our database name

2024-01-18 00:01 UTC, IritaSee commented on .env.example
This is just an `example` , I don't think that we need to change this, just to be sure in the real `.env` has matching database name

2024-01-18 03:46 UTC, DiyArc-350 commented on .env.example
will do bang, i'm more concern for the seeders bang. Since it holds quite the information for the recruitment. Is there anything i should do for that?

2024-01-18 05:05 UTC, fakhrip commented on .env.example
Correct, let me finish my full review and get back to you on this one, i will post it around 4PM today 👍

2024-01-18 12:03 UTC, fakhrip requested changes
Sorry i dont pinpoint any of the codes that you need to change because there are too many changes here and it makes my browser lags XD, but here are the changes that you have to do:

- Remove all of the commented codes that are no longer of use
- Remove all the seeders file since there are important informations that shouldnt be leaked to the caas (keep in mind that this codebase/repository is an open/public one so everyone could see it even if they are not part of this organization)

2024-01-19 14:00 UTC, fakhrip approved these changes
Nice! Looks good to me

2024-01-21 14:56 UTC, IritaSee approved these changes

2024-01-21 14:56 UTC, IritaSee commented
LGTM! Merging to master

2024-01-21 14:56 UTC, merged