Add requested feature, hidden create admin feature and some fix
Daskom-Lab/daskomrec24 pull request #4
Opened 2024-01-23 10:07 UTC by DiyArc-350

So, due to my negligence, I did not write a proper commit message, thus i'm going to inform what my last three commit does.

1. Feat(roles): add quota feature for roles
2. Feat(admin): add hidden features for creating an admin account
3. Fix: minor typo, change data type for 'nohp', and method to get target id

2024-01-23 19:33 UTC, IritaSee commented on app/Http/Controllers/Auth/CaasLoginController.php
> +        DataCaas::where('id', $id)->update([
I am a bit afraid since now, all we need to change someone's password, is _simpy_ their ID. Hopefully this function is always triggered inside authentication

2024-01-23 19:34 UTC, IritaSee commented on app/Http/Controllers/Auth/CaasLoginController.php
> +        DataCaas::where('id', $id)->update([
Or, my laravel knowledge is quite expired XD

2024-01-23 19:41 UTC, IritaSee commented on app/Http/Controllers/DataCaasController.php
> +        if ($request->oldRoleId != $request->roles_id) {
Just want to make sure, `Role` here (in Caas domain) means their recruitment stage right?

2024-01-23 19:42 UTC, IritaSee commented on app/Http/Controllers/DataCaasController.php
> +        if ($request->oldRoleId != $request->roles_id) {
or _something_ inside recruitment??

2024-01-23 19:45 UTC, IritaSee commented on database/migrations/2024_01_11_072235_create_assistantcontacts_table.php
> +            $table->string('nohp');
Nice catch! ;)

2024-01-23 19:46 UTC, IritaSee commented on resources/views/admin/adminList.blade.php
> +@extends('admin.partials.index')
TLDR; but since this one is frontend templating, I am sure this is tested!

2024-01-23 19:50 UTC, IritaSee approved these changes, later dismissed
So far, looks good to me!
But yeah, I think my laravel knowledge is quite lame and the best practice is quite different now...

I think other reviewers should check the reset password for caas part.. that's quite suspicious

2024-01-23 22:57 UTC, fakhrip commented
Ping me once you've replied to @IritaSee comments above @DiyArc-350, thanks!

I will start reviewing by then.

2024-01-24 04:43 UTC, DiyArc-350 commented on app/Http/Controllers/Auth/CaasLoginController.php
> +        DataCaas::where('id', $id)->update([
i made this for the admin also (same code), in the form and route the request is set to post, and the id is fetched from auth()->guard('admin')->user()->id, and yes the route is accessible when user is logged in. is it safe? or should i make a change?

2024-01-24 04:55 UTC, DiyArc-350 commented on app/Http/Controllers/DataCaasController.php
> +        if ($request->oldRoleId != $request->roles_id) {
is a new idea for the this recruitment since our theme is dungeon and RPG related. the caas can only choose their role in upgrading stage, with a certain period of time, the system is similar to choose schedule, thus i made a switch for the choose role for more flexibility. 

Fyi, i'm just making the admin functions, the caas functions is handled by the other backend.

2024-01-24 04:57 UTC, DiyArc-350 commented on database/migrations/2024_01_11_072235_create_assistantcontacts_table.php
> +            $table->string('nohp');
yoi

2024-01-24 05:00 UTC, DiyArc-350 commented on resources/views/admin/adminList.blade.php
> +@extends('admin.partials.index')
it works wonder!

2024-01-25 02:19 UTC, IritaSee commented on app/Http/Controllers/Auth/CaasLoginController.php
> +        DataCaas::where('id', $id)->update([
@fakhrip is that safe to do?

2024-01-25 02:19 UTC, IritaSee commented
I think you can start the review now @fakhrip , I ping you in a convo related to my concern

2024-01-25 07:27 UTC, fakhrip commented on app/Http/Controllers/Auth/CaasLoginController.php
> +        DataCaas::where('id', $id)->update([
oh yeah this is absolutely safe, thats fine 👍

2024-01-25 07:34 UTC, fakhrip requested changes
Just need one minor change, anyway this is one good looking PR, good job and keep up the good work! 🔥

2024-01-25 07:34 UTC, fakhrip commented on .gitignore
> +composer.lock
`composer.lock` file shouldnt be ignored from a git repo, since this will act as a cache later to ease deployment, please remove this one from this file 👍

2024-01-25 08:21 UTC, fakhrip approved these changes

2024-01-25 08:21 UTC, merged

2024-01-26 06:26 UTC, IritaSee commented on .gitignore
> +composer.lock
I just knew this XD