Frontend Pages Integration, Add CaAs feature and Add routes
Daskom-Lab/daskomrec24 pull request #7
Opened 2024-03-03 04:47 UTC by DiyArc-350

Details

- Excluding the public assets of caas to protect DLOR 2024 privacy.
- still have an anomaly in the implementation of the sword cursor in the landing page.

2024-03-05 07:04 UTC, fakhrip requested changes
Can you guys please confirm and/or reply to my comments first, thanks!

2024-03-05 07:04 UTC, fakhrip commented on app/Http/Controllers/Auth/CaasLoginController.php
> +            'old_password' => 'required|string',
Have you confirmed that giving incorrect old password wont pass this check? @DiyArc-350 

because i believe you should have put this rule too https://laravel.com/docs/10.x/validation#rule-current-password for the validation to work properly

2024-03-05 07:04 UTC, fakhrip commented on app/Http/Controllers/CaasController.php
> +        }
```suggestion
        if (!Auth::guard('caas')->user()->status->isPass || !Auth::guard('caas')->user()->announcecheck()->isPlotActive) {
            return redirect()->route('caas.dashboard');
        } elseif (boolval(Auth::guard('caas')->user()->plots)) {
            return redirect()->route('caas.fix.schedule');
        }
```

its better to write it this way for idiomatic reason, otherwise it would be awkward to do comparison just to make it boolean when 0 already means false and >=1 already means true in boolean world

2024-03-05 07:04 UTC, fakhrip commented on app/Http/Controllers/CaasController.php
> +        if ($shift->quota <= 0 || Auth::guard('caas')->user()->announcecheck()->isPlotActive == 0) {
```suggestion
        if ($shift->quota <= 0 || !Auth::guard('caas')->user()->announcecheck()->isPlotActive) {
```

same as the other one

2024-03-05 07:04 UTC, fakhrip commented on app/Http/Controllers/CaasController.php
> +        if (boolval(Auth::guard('caas')->user()->plots) == 0) {
```suggestion
        if (!boolval(Auth::guard('caas')->user()->plots)) {
```

2024-03-05 07:04 UTC, fakhrip commented on app/Http/Controllers/CaasController.php
> +        }
```suggestion
        if (!Auth::guard('caas')->user()->status->isPass || Auth::guard('caas')->user()->role->roles_id != 1 || !Auth::guard('caas')->user()->announcecheck()->isRoleActive) {
            return redirect()->route('caas.fix.role');
        }
```

Actually, these validation should have existed in the routes/web.php, are there any reason why you guys didnt put it there instead? @DiyArc-350

2024-03-05 07:04 UTC, fakhrip commented on app/Http/Controllers/CaasController.php
> +        }
```suggestion
        if (Auth::guard('caas')->user()->role->roles_id == 1 || !Auth::guard('caas')->user()->status->isPass || Auth::guard('caas')->user()->status->stages->stagesName != "Upgrading") {
            return redirect()->route('caas.dashboard');
        }
```

2024-03-05 07:04 UTC, fakhrip commented on resources/views/caas/schedule.blade.php
> +                    @endforeach
you guys should follow this instead https://stackoverflow.com/questions/50864982/getting-the-position-index-of-an-object-in-foreach, do not use native php inside blade this way, otherwise it will confuse everyone 😅

2024-03-06 07:34 UTC, DiyArc-350 commented on app/Http/Controllers/CaasController.php
> +        }
noted bang, so i can just commit the suggestion bang?

2024-03-06 07:53 UTC, DiyArc-350 commented on app/Http/Controllers/CaasController.php
> +        }
I didn't find a better way to make this caas validation more efficient, but I tried to reduce the code length by joining the table inside the model, thus i have to validate the caas guard frequently, also the route for both caas and admin are already protected.

2024-03-06 07:55 UTC, DiyArc-350 commented on resources/views/caas/schedule.blade.php
> +                    @endforeach
hehehe, i will change that bang

2024-03-06 08:08 UTC, fakhrip commented on app/Http/Controllers/CaasController.php
> +        }
sure you can do that too, but please check the other one as well that looks like pretty much the same thing

2024-03-06 08:11 UTC, fakhrip commented on app/Http/Controllers/CaasController.php
> +        }
i see, so the point here is that i think you havent realized that there is this thing called middleware https://laravel.com/docs/10.x/middleware, you can use that instead so for every single route in which you need to do the custom check and validation, you can just reuse that middleware, can you use this instead?

2024-03-06 08:11 UTC, fakhrip commented on app/Http/Controllers/CaasController.php
> +        }
this is an important concept in backend development, so it might as well serve as something that you can practice too 👍

2024-03-06 08:12 UTC, fakhrip commented on resources/views/caas/schedule.blade.php
> +                    @endforeach
sure no problem 😄

2024-03-06 08:12 UTC, DiyArc-350 commented on app/Http/Controllers/Auth/CaasLoginController.php
> +            'old_password' => 'required|string',
it wont pass the check bang, after the validation code there's a hash check for the password

2024-03-06 08:13 UTC, fakhrip commented
You can push all the requested changes here, and then re-request my review once you have done it all @DiyArc-350 , feel free to ask any question if you want, and tag me so i can get an email notification too 👍

2024-03-06 09:03 UTC, DiyArc-350 commented on app/Http/Controllers/CaasController.php
> +        }
will do bang

2024-03-06 09:31 UTC, fakhrip commented on app/Http/Controllers/Auth/CaasLoginController.php
> +            'old_password' => 'required|string',
I see, i think i missed that one, sure, we're good then for this one 👍

2024-03-07 13:49 UTC, DiyArc-350 commented on app/Http/Controllers/CaasController.php
> +        }
done bang @fakhrip

2024-03-07 15:18 UTC, fakhrip approved these changes
Alright, this looks good enough, good job @DiyArc-350 !

2024-03-07 15:19 UTC, merged